name: scan-sdk-image

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: '20 17 * * *'  # Runs daily at 17:20 UTC

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan SDK base image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: mcr.microsoft.com/dotnet/sdk:8.0.412-bookworm-slim
          exit-code: '1'
