name: scan-sdk-image

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: '20 17 * * *'  # Runs daily at 17:20 UTC

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan SDK base image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: node:24.9.0-alpine3.22@sha256:f8baf2c963e3bff767993135ae3447bb433e8d64a5e4bb65780cd29ef3a525c2
          exit-code: '1'
